check_updates:
  description: Check for Tasmota Receiver updates.
  
update_component:
  description: Update Tasmota Receiver component.

set_balance:
  name: Set Balance
  description: Set the zone balance level.
  target:
    entity:
      integration: tasmota_receiver
      domain: media_player
  fields:
    level:
      description: integer from 0 to 20 inclusive, where 0 is -10(left), 0 is center and 20 is +10 (right).
      required: true
      example: "10"
      default: "0"

set_bass:
  name: Set Bass
  description: Set the bass level.
  target:
    entity:
      integration: tasmota_receiver
      domain: media_player
  fields:
    level:
      description: Integer from 0 to 14 inclusive.
      required: true
      example: "10"
      default: "7"
  
set_treble:
  name: Set Treble
  description: Set treble level.
  target:
    entity:
      integration: tasmota_receiver
      domain: media_player
  fields:
    level:
      description: Integer from 0 to 14 inclusive.
      required: true
      example: "10"
      default: "7"