snapshot:
  target:
    entity:
      integration: monoprice
      domain: media_player

restore:
  target:
    entity:
      integration: monoprice
      domain: media_player

set_front_left:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: integer from 0 to 20 inclusive, where 0 is -10(left), 0 is center and 20 is +10 (right).
      required: true
      example: "10"
      default: "0"

set_front_right:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: integer from 0 to 20 inclusive, where 0 is -10(left), 0 is center and 20 is +10 (right).
      required: true
      example: "10"
      default: "0"

set_center:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: integer from 0 to 20 inclusive, where 0 is -10(left), 0 is center and 20 is +10 (right).
      required: true
      example: "10"
      default: "0"

set_rear_left:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: integer from 0 to 20 inclusive, where 0 is -10(left), 0 is center and 20 is +10 (right).
      required: true
      example: "10"
      default: "0"

set_rear_right:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: integer from 0 to 20 inclusive, where 0 is -10(left), 0 is center and 20 is +10 (right).
      required: true
      example: "10"
      default: "0"

set_subwoofer:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: integer from 0 to 20 inclusive, where 0 is -10(left), 0 is center and 20 is +10 (right).
      required: true
      example: "10"
      default: "0"

set_balance:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: integer from 0 to 20 inclusive, where 0 is -10(left), 0 is center and 20 is +10 (right).
      required: true
      example: "10"
      default: "0"

set_bass:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: Integer from 0 to 14 inclusive.
      required: true
      example: "10"
      default: "7"

set_middle:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: Integer from 0 to 14 inclusive.
      required: true
      example: "10"
      default: "7"
  
set_treble:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: Integer from 0 to 14 inclusive.
      required: true
      example: "10"
      default: "7"
